### ISSUE TITLE
Hello?this ubuntu version cannot work?

### ISSUE THREAD

**Issue by 459737087** [XuShengpan/PCDViewer#1]
could you give me some advice?

**Comment by XuShengpan** [comment]
1. Install (download ) the correct version of PCDViewer according to you Ubuntu version. There are two versions for Ubuntu, i.e. PCDViewer-ubuntu18.04 and PCDViewer-ubuntu20.04 ;
2. If it prompted can not find shared libraries, add the install directory of PCDViewer to /etc/ld.so.conf , and run sudo ldconfig - v to make the changes effective.

**Comment by XuShengpan** [comment]
Solved.
